-- Timestamps (only where missing)
ALTER TABLE WarehouseLocations
  ADD COLUMN created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ShopLocations
  ADD COLUMN created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Pickers
  ADD COLUMN created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Boxes
  ADD COLUMN created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE OrderItems
  ADD COLUMN created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;

-- Inventory tables
ALTER TABLE ProductWarehouseStock
  ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ProductShopStock
  ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;

-- Data-quality: keep your existing checks, add the cross-check
ALTER TABLE OrderItems
  ADD CONSTRAINT chk_oi_picked_le_ordered CHECK (qty_picked <= qty_ordered);

-- Optional: clarify intent with UNSIGNED
ALTER TABLE OrderItems
  MODIFY qty_ordered INT UNSIGNED NOT NULL,
  MODIFY qty_picked  INT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE ProductWarehouseStock
  MODIFY qty_on_hand INT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE ProductShopStock
  MODIFY qty_on_hand INT UNSIGNED NOT NULL DEFAULT 0;
